apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      nodeName: ubuntu
      containers:
        - name: loadgen-container
          image: harbor.mgmt.vintecc.cloud/vtc_cld-thesis-gilles/loadgen:updated
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: app-volume
      volumes:
        - name: app-volume
          hostPath:
            path: /root/loadgen
            type: Directory
      # nodeSelector:
      #   node-role.kubernetes.io/edge: ""
      # openyurt.io/is-edge-worker: "true"
      #   type: "virtual-kubelet"
      # tolerations:
      #   - key: virtual-kubelet.io/provider
      #     operator: Equal
      #     value: backend
      #     effect: NoSchedule
