apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yurt-manager-yurt-coordinator-cert-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yurt-manager-yurt-coordinator-cert-controller
subjects:
  - kind: ServiceAccount
    name: yurt-manager
    namespace: kube-system
